In [1]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: pandas in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.5.2)
Requirement already satisfied: matplotlib in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (2.5.2)
Requirement already satisfied: packaging>=20.0 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Requirement already satisfied: seaborn in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (2.5.2)
Requirement already satisfied: pandas>=1.2 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.0.5)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from seaborn) (3.11.1)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.3)
Requirement already satisfied: pillow>=9 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas>=1.2->seaborn) (2026.3)
Requirement already satisfied: six>=1.5 in C:\Users\maica\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Requirement already satisfied: openpyxl in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\maica\AppData\Local\Programs\Python\Python314\Lib\site-packages (from openpyxl) (2.0.0)

In [2]:
#Importamos librerías requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Citas_Digital.xlsx')
df

,BDC,Fecha,Nombre Cliente,Telefono,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado,¿Por que no ha visitado la agencia?,¿Por que no hay solicitud de credito?,¿Por que no hubo prueba de manejo ?,¿Por que no hubo proceso wow?,¿Por que se asigno antes de vistar piso?,Unnamed: 15
0,Saul,NaT,Guillermo,NaN,Finalizado,0.9,1.0,0.0,0.0,Nancy,"Ya visito la Agencia el dia jueves 17, intere...","Pide arrendamiento, unicamente se esta en espe...","Si, hizo prueba de manejo","Si recibio procesos wow, estuvo en la agencia ...","No, se espero a que visitara la agencia para s...",Comenta que no se le hizo atractivo el arrenda...
1,Saul,NaT,Roberto,NaN,Finalizado,0.4,0.0,0.0,0.0,Victor,Ya visito la Agencia el dia 3 de abril,Por que primero queria manejar las unidad,No habia unidad GS8 HEV para prueba de manejo,"Si recibio procesos wow, sin embargo no quizo ...",Se asigno hasta que visitara Piso,NaN
2,Saul,NaT,Irving,NaN,Finalizado,0.85,0.0,0.0,0.0,Alan,Ya visito la agencia el dia 21 de abril,"Firmo solicitud, sin embargo despues comento q...",Por que no habia unidad para prueba de manejo,"Si se realizo el proceso wow, los clientes se ...",Se asigno hasta que visitara Piso,Se le manda msj de seguimiento 03/05/2025
3,Saul,NaT,Oswaldo,NaN,Venta,0.9,0.0,0.0,1.0,Mauricio,El cliente vive en Tabasco Villahermosa,Sera compra de contado,"Ya la manejo en Villahermosa, sin embargo por ...","Las veces que se le ha marcado, agradece mucho...","Necesitabamos sacar el apartado, por eso se as...",NaN
4,Saul,NaT,Rodrigo,NaN,Finalizado,0.9,1.0,0.0,0.0,Mauricio,"Visito la agencia el mes pasado, y nos visita ...",Hoy visita nuevamente la agencia y se firma so...,"La primera vez que nos visito, realizo PDM",Si recibio el proceso wow la primera vez que n...,Se asigno hasta que visitara Piso la primera ...,Por el detalle del carbilink compro en otra ma...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1048570,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048571,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048572,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048573,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1048574,NaN,NaT,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
#Verificamos información del DataFrame
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column                                    Non-Null Count    Dtype
---  ------                                    --------------    -----
 0   BDC                                       673 non-null      object
 1   Fecha                                     88 non-null       datetime64[us]
 2   Nombre Cliente                            668 non-null      object
 3   Telefono                                  2 non-null        str
 4   Estatus de Lead                           654 non-null      object
 5   Potencial de compra                       614 non-null      object
 6   PDM                                       1048574 non-null  float64
 7   SDC                                       1048573 non-null  float64
 8   Venta                                     1048570 non-null  float64
 9   Asesor Asignado                           656 non-null      str
 10  ¿Por que no ha visitado la agencia?       493 non-null      str
 11  ¿Por que no hay solicitud de credito?     379 non-null      str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null      str
 13  ¿Por que no hubo proceso wow?             364 non-null      str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null      str
 15  Unnamed: 15                               16 non-null       str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 128.0+ MB

In [5]:
#Paso 1 - Filtro por filas
filtro1 = df.iloc[0:673, :]
filtro1.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 16 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   BDC                                       657 non-null    object
 1   Fecha                                     72 non-null     datetime64[us]
 2   Nombre Cliente                            652 non-null    object
 3   Telefono                                  2 non-null      str
 4   Estatus de Lead                           638 non-null    object
 5   Potencial de compra                       599 non-null    object
 6   PDM                                       672 non-null    float64
 7   SDC                                       671 non-null    float64
 8   Venta                                     668 non-null    float64
 9   Asesor Asignado                           641 non-null    str
 10  ¿Por que no ha visitado la agencia?       493 non-null    str
 11  ¿Por que no hay solicitud de credito?     379 non-null    str
 12  ¿Por que no hubo prueba de manejo ?       355 non-null    str
 13  ¿Por que no hubo proceso wow?             364 non-null    str
 14  ¿Por que se asigno antes de vistar piso?  353 non-null    str
 15  Unnamed: 15                               16 non-null     str
dtypes: datetime64[us](1), float64(3), object(4), str(8)
memory usage: 84.3+ KB

In [ ]:
#Paso 2 - Filtro por columnas
filtro2 = filtro1.iloc[:, [0,1,2,4,5,6,7,8,9]]
filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    object
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    object
 3   Estatus de Lead      638 non-null    object
 4   Potencial de compra  599 non-null    object
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(3), object(4), str(1)
memory usage: 47.4+ KB

In [11]:
#Limpieza y conversión de Potencial de compra a float

filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("Ventas ","0", regex=False)
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("%","", regex=False)
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace('"',"", regex=False)
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("&","", regex=False)

filtro2['Potencial de compra'] = filtro2['Potencial de compra'].astype(float)

filtro2.info()

ValueError: could not convert string to float: "8'"

In [13]:
#Paso 3 - Convertir Potencial de compra a float
filtro2["Potencial de compra"] = filtro2["Potencial de compra"].astype(float)
filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    object
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    object
 3   Estatus de Lead      638 non-null    object
 4   Potencial de compra  5 non-null      float64
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(4), object(3), str(1)
memory usage: 47.4+ KB

In [12]:
#Limpieza y conversión de Potencial de compra a float

filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("Ventas ","0", regex=False)
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("%","", regex=False)
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("'","", regex=False)
filtro2['Potencial de compra'] = filtro2['Potencial de compra'].str.replace("&","", regex=False)

filtro2['Potencial de compra'] = filtro2['Potencial de compra'].astype(float)

filtro2.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    object
 1   Fecha                72 non-null     datetime64[us]
 2   Nombre Cliente       652 non-null    object
 3   Estatus de Lead      638 non-null    object
 4   Potencial de compra  5 non-null      float64
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: datetime64[us](1), float64(4), object(3), str(1)
memory usage: 47.4+ KB

In [14]:
#Paso 4 - Crear CSV General
filtro2.to_csv("Citas_Digital_General.csv", index=False)

In [15]:
df_general = pd.read_csv("Citas_Digital_General.csv")
df_general.info()

<class 'pandas.DataFrame'>
RangeIndex: 673 entries, 0 to 672
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   BDC                  657 non-null    str
 1   Fecha                72 non-null     str
 2   Nombre Cliente       652 non-null    str
 3   Estatus de Lead      638 non-null    str
 4   Potencial de compra  5 non-null      float64
 5   PDM                  672 non-null    float64
 6   SDC                  671 non-null    float64
 7   Venta                668 non-null    float64
 8   Asesor Asignado      641 non-null    str
dtypes: float64(4), str(5)
memory usage: 47.4 KB

In [16]:
#Se vuelve a leer el archivo general
df_general = pd.read_csv("Citas_Digital_General.csv")
df_general

,BDC,Fecha,Nombre Cliente,Estatus de Lead,Potencial de compra,PDM,SDC,Venta,Asesor Asignado
0,Saul,NaN,Guillermo,Finalizado,NaN,1.0,0.0,0.0,Nancy
1,Saul,NaN,Roberto,Finalizado,NaN,0.0,0.0,0.0,Victor
2,Saul,NaN,Irving,Finalizado,NaN,0.0,0.0,0.0,Alan
3,Saul,NaN,Oswaldo,Venta,NaN,0.0,0.0,1.0,Mauricio
4,Saul,NaN,Rodrigo,Finalizado,NaN,1.0,0.0,0.0,Mauricio
...,...,...,...,...,...,...,...,...,...
668,Ignacio,2026-07-21,Carlos Balderrama,Activo,NaN,1.0,1.0,1.0,Mario Varela
669,Ignacio,2026-07-21,Andrés Netzahuatl,Activo,NaN,0.0,0.0,0.0,Mauricio
670,Ana,2026-07-22,Arat Israel,Activo,80.0,1.0,1.0,0.0,Aurelio
671,Ana,2026-07-22,Maira Escalante,Activo,NaN,1.0,1.0,0.0,Pedro Antonio
672,Ignacio,2026-07-22,Zaira Macip,Activo,NaN,0.0,0.0,0.0,Aurelio

In [17]:
#Convertir la columna Fecha a formato fecha
df_general["Fecha"] = pd.to_datetime(df_general["Fecha"])

In [18]:
#ABRIL
abril_2025 = df_general[
    (df_general["Fecha"].dt.month == 4) &
    (df_general["Fecha"].dt.year == 2025)
]

abril_2025.to_csv("Abril_2025.csv", index=False)

In [19]:

#MAYO
mayo_2025 = df_general[
    (df_general["Fecha"].dt.month == 5) &
    (df_general["Fecha"].dt.year == 2025)
]

mayo_2025.to_csv("Mayo_2025.csv", index=False)

In [20]:
#JUNIO
junio_2025 = df_general[
    (df_general["Fecha"].dt.month == 6) &
    (df_general["Fecha"].dt.year == 2025)
]

junio_2025.to_csv("Junio_2025.csv", index=False)

In [21]:
#JULIO 
julio_2025 = df_general[
    (df_general["Fecha"].dt.month == 7) &
    (df_general["Fecha"].dt.year == 2025)
]

julio_2025.to_csv("Julio_2025.csv", index=False)

In [22]:
#AGOSTO 
agosto_2025 = df_general[
    (df_general["Fecha"].dt.month == 8) &
    (df_general["Fecha"].dt.year == 2025)
]

agosto_2025.to_csv("Agosto_2025.csv", index=False)

In [23]:
#SEPTIEMBRE
septiembre_2025 = df_general[
    (df_general["Fecha"].dt.month == 9) &
    (df_general["Fecha"].dt.year == 2025)
]

septiembre_2025.to_csv("Septiembre_2025.csv", index=False)

In [24]:
#OCTUBRE
octubre_2025 = df_general[
    (df_general["Fecha"].dt.month == 10) &
    (df_general["Fecha"].dt.year == 2025)
]

octubre_2025.to_csv("Octubre_2025.csv", index=False)

In [25]:
#NOVIEMBRE 
noviembre_2025 = df_general[
    (df_general["Fecha"].dt.month == 11) &
    (df_general["Fecha"].dt.year == 2025)
]

noviembre_2025.to_csv("Noviembre_2025.csv", index=False)

In [26]:
#DICIEMBRE
diciembre_2025 = df_general[
    (df_general["Fecha"].dt.month == 12) &
    (df_general["Fecha"].dt.year == 2025)
]

diciembre_2025.to_csv("Diciembre_2025.csv", index=False)

In [27]:
#ENERO 26
enero_2026 = df_general[
    (df_general["Fecha"].dt.month == 1) &
    (df_general["Fecha"].dt.year == 2026)
]

enero_2026.to_csv("Enero_2026.csv", index=False)

In [28]:
#FEBRERO 26
febrero_2026 = df_general[
    (df_general["Fecha"].dt.month == 2) &
    (df_general["Fecha"].dt.year == 2026)
]

febrero_2026.to_csv("Febrero_2026.csv", index=False)

In [29]:
#MARZO 26
marzo_2026 = df_general[
    (df_general["Fecha"].dt.month == 3) &
    (df_general["Fecha"].dt.year == 2026)
]

marzo_2026.to_csv("Marzo_2026.csv", index=False)

In [30]:
#ABRIL 26
abril_2026 = df_general[
    (df_general["Fecha"].dt.month == 4) &
    (df_general["Fecha"].dt.year == 2026)
]

abril_2026.to_csv("Abril_2026.csv", index=False)

In [31]:
#MAYO 26
mayo_2026 = df_general[
    (df_general["Fecha"].dt.month == 5) &
    (df_general["Fecha"].dt.year == 2026)
]

mayo_2026.to_csv("Mayo_2026.csv", index=False)

In [32]:
#JUNIO 26
junio_2026 = df_general[
    (df_general["Fecha"].dt.month == 6) &
    (df_general["Fecha"].dt.year == 2026)
]

junio_2026.to_csv("Junio_2026.csv", index=False)

In [33]:
#JULIO 26
julio_2026 = df_general[
    (df_general["Fecha"].dt.month == 7) &
    (df_general["Fecha"].dt.year == 2026)
]

julio_2026.to_csv("Julio_2026.csv", index=False)